### ISSUE TITLE
bootstrapのgemを導入

### ISSUE THREAD

**Issue by shimada-yuji** [kaitori/kaitori-web#22]

**Comment by registak** [comment]
https://github.com/twbs/bootstrap-sass
↑参考に入れたんですが、

```css
@import "bootstrap-sprockets";
@import "bootstrap";
```
今ってこうするだけで適応できた。
rails3系?昔は確か直接 assets/stylesheetsに入ってはずと思って。
つまり何が言いたいかっていうと、bootstrap-sassのテンプレートをべ―スに
デザイン上がったやつは適応していこうと話してたと思うんやが、
下記のようにやる方向で問題ない？

https://github.com/twbs/bootstrap-sass#configuration

http://qiita.com/masamitsu-konya/items/e3630046774ac1fbd346
(特にページの1番下参照)

**Comment by shimada-yuji** [comment]
確認した！上記の方法でも問題ないと思う！
